// Global constant file
export const Constants = Object.freeze({
    url:{
        getVideoCount: 'videoDetails/getVideoCount',
        getStageDetails: 'videoDetails/getStageDetails',
        getShowDetails: 'videoDetails/getShowDetails',
        checkSlugExistence: 'create/checkUniqueIdentity',
        uploadVideo: 'create',
        getArtistListing: 'artist/getArtistListing',
        sentArtistToReview: 'artist/sendToReview',
        sentCollectionToReview: 'collection/sendToReview',
        sentShowToReview: 'show/sendToReview',
        getArtistTabCount: 'artist/getArtistCount',
        getUnbindArtistVideoList: 'artist/getArtistVideo',
        getGenreSubGenreList: 'meta/getGenreSubGenre',
        updateArtistDetail: 'artist/saveArtist',
        viewArtistDetail:'artist/getArtist',
        getCollectionTabCount: 'collection/getCollectionCount',
        getCollectionListing: 'collection/getCollectionListing',
        viewCollectionDetail: 'collection/getCollection',
        getCategoryList: 'meta/getCategories',
        getShowTabCount: 'show/showCount',
        getShowListing: 'show/shows',
        sentIndividualToReview: 'episode/sendToReview',
        getIndividualTabCount: 'episode/episodeCount',
        getIndividualListing: 'episode/episode',
        viewIndividualDetail: 'episode/EpisodeDetailBySlug',
        getVideoList: 'collection/getVideosList',
        getShowVideoList: 'show/getShowVideos',
        getIndividualVideoList: 'episode/getVideosList',
        uploadImage: 'common/imageOperation',
        checkSlug: 'common/checkSlug',
        updateCollectionDetail: 'collection/saveCollection',
        updateIndividualDetail: 'episode/saveIndividualEpisode',
        viewShowDetail: 'show/getShowDetail',
        updateShowDetail: 'show/saveShow',
        saveVideoDetails: 'videoDetails/saveVideoDetails',
        getAllVideoDetail: 'videoDetails/getAllVideoDetail',
        getIndividualArtistListing: 'common/getArtists',
        removeVideo: 'common/removeVideo',
        getReviewAndPublishAndActiveCount: 'common/getReviewAndPublishAndActiveCount',
        getReviewActiveListing: 'common/getReviewAndActiveData',
        getPublishListing: 'common/getPublishData',
        moveToStage: 'common/moveToStage',
        sendToCorrection: 'common/changeStatus',
        publishNow: 'common/publish',
    },
    image:{
        hls: '/HLS/',

        artistSmall:'/44/',
        artistMedium:'/60/',
        artistLarge100:'/100/',
        artistLarge200:'/200/',

        verticalSmall : '/vertical/small/',
        verticalMedium : '/vertical/large/',
        verticalOriginal: '/vertical/',

        horizontalSmall : '/horizontal/small/',
        horizontalMedium : '/horizontal/medium/',
        horizontalLarge: '/horizontal/large/',

        squareSmall : '/square/small/',
        squareMedium : '/square/medium/',       
        squareLarge : '/square/large/',
        square: '/square/',        
    },
});